services:
  - type: web
    name: vit-hackathon-api
    runtime: docker
    rootDir: backend
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SUBMISSION_DEADLINE
        value: "2026-12-31T23:59:59Z"
